### ISSUE TITLE
Rosetta Code version of Anagrams

### ISSUE THREAD

**Issue by celtic-coder** [burningrooftop/anagram#1]
Hi Neal (@burningrooftop),

Have you considered the Seed7 version of [Anagrams](https://rosettacode.org/wiki/Anagrams#Seed7) on Rosetta Code? Or were already familiar with the C version and wanted to implement this specific one in Seed7?

Kind Regards,
Liam

**Comment by burningrooftop** [comment]
Hi Liam,

When I'm learning a new language, one of the programs I always write is an anagrams program - it gives me a feel for how I will like the language. Plus, because my version can be limited to only return anagrams of a certain length, it it handy for cheating in a certain 5 letter word game :)

- Neal

**Comment by celtic-coder** [comment]
Hi Neal (@burningrooftop),

Ah, yes. That's an excellent strategy! I've been doing a bit with Seed7 and it is a  well thought out and comprehensive language. The only thing missing would be JSON support, but otherwise it is an excellent language.

Kind Regards,
Liam
